### ISSUE TITLE
Congrats and small demands

### ISSUE THREAD

**Issue by fahimaltinordu** [coinables/NoNodePay#1]
Congratulations, it looks awesome.
Regarding admin panel, edit option works well but remove item/product not works.

For main page, it would be nice if there is "remove from cart" option.

Thank you for this awesome product

**Comment by coinables** [comment]
You can adjust the inventory to hide the item if you don't want an item to display on the main page.     

To actually delete we could add an additional submit button that would allow deleting an item from the database.      

`<input type="submit" id="del" name="delete" value="Delete">`

```
if(isset($_POST['delete']))
{
   
   $queryDelete = "DELETE FROM products WHERE id = '$product'";
  $doDelete = mysqli_query($conn, $queryDelete) or die(mysqli_error($conn));
  $message = "<h3>Item Removed</h3>";
  //update form 
  $queryItem = "SELECT * FROM products WHERE id = '$product'";
  $doItem = mysqli_query($conn, $queryItem) or die(mysqli_error($conn));
  $fetchItem = mysqli_fetch_assoc($doItem);
  $iname = $fetchItem['name'];
  $iprice = $fetchItem['price'];
  $idesc = $fetchItem['description'];
  $iimage = $fetchItem['image'];
  $istock = $fetchItem['in_stock'];
}
```

We could add a button next to each item in the cart, and store the array key as the button value, 
Then could simply use `unset($cart[$key])`

I will look at adding these suggestions soon.

**Comment by fahimaltinordu** [comment]
Many thanks, i really like this solution. Btw, how confirmation works for payment status? Does it use unconfirmed balance like if $btcOwed = unconfirmed balance or similar?

Also maybe we should change &#x0E3F, it is the symbol of thai baht

**Comment by coinables** [comment]
I use blockchain.info to check confirmed vs unconfirmed. If no confirmations then I check for unconfirmed, if no unconfirmed either then that means no payment. See lines https://github.com/coinables/NoNodePay/blob/57075980212c861c869be05521da7d48af1a7274/admin.php#L33

**Comment by coinables** [comment]
https://github.com/coinables/NoNodePay/commit/86640b7e12b2cc7db0eb5a7ddabc154e8962aecd
