### ISSUE TITLE
QR Code bad showing

### ISSUE THREAD

**Issue by Olaf1607** [coinables/NoNodePay#2]
Hello,

Firstly, thanks for your great script !

I have an error when the QR Code is generated.
Here is a printscreen : [https://imgur.com/FpGn6g1](url)

Do you have an idea why this bad showing ?

Many thanks in advance.

**Comment by coinables** [comment]
The QR code portion uses qrcodejs (https://davidshimjs.github.io/qrcodejs/). I quickly looked through the posted issues on that repo, and could not find someone with the same issue. Did you add any additional JS libraries to the page? Can you run with the developer console open and see if there are any errors in the console?

**Comment by Olaf1607** [comment]
No I don't added any additional JS libraries.
But perhaps any way, the script is installed on a .onion URL, so I use Tor Browser. When I use my Windows computer, I have this bad showing, and when I use my Android phone the QR Code is perfectly showed.
It's probably a bug with the Tor Browser Windows version, no ?

**Comment by coinables** [comment]
Ok, seems like it is related to the Tor browser, I found this which could be related (https://gitlab.torproject.org/legacy/trac/-/issues/27543).

For now you can try changing `pay.php` lines 69 - 71 and use the google API to create the QR code and see if that works (downside is you're pinging google).  

In pay.php replace lines 69-71 with the below and see if that works:
`<img src="http://chart.googleapis.com/chart?chs=125x125&cht=qr&chl=<?php echo $_SESSION['payTo']; ?>" width="50%">`

**Comment by Olaf1607** [comment]
After to change the pay.php lines, it works now, the QR Code is perfectly showed.
Thanks for your support !

**Comment by coinables** [comment]
Good to hear that it is working now. I'm going to close this issue as it appears to be a Tor browser issue.
